### ISSUE TITLE
Support aarch64-linux

### ISSUE THREAD

**Issue by slice** [rapenne-s/bento#4]
Hi! I was pointed to Bento as a simple and effective solution to deploying NixOS configurations. However, one of my servers is aarch64-linux and isn't supported by Bento (I can't run `nix shell github:rapenne-s/bento`).

It doesn't look like Bento depends on anything x86_64 specific. Could support be added easily?

**Comment by rapenne-s** [comment]
Hello,

This is something that should be solved indeed. There is nothing x86-64 specific in Bento, the flake should be modified to support all architectures.

**Comment by rapenne-s** [comment]
This should be fixed now
